// Seed script for client health data
// Run via: npx tsx scripts/seed-client-health.ts

const DASHBOARD_URL = process.env.DASHBOARD_URL || 'https://nodefy-sales-dashboard.vercel.app'

const clients = [
  {
    clientName: 'Corendon Hotels',
    accountManager: 'Koen',
    vertical: 'Hospitality',
    contractStart: '2024-06-01',
    contractEnd: '2026-06-01',
    retainerValue: 4500,
    platforms: ['meta', 'google'],
    healthScore: 92,
    scores: { performance: 95, budgetPacing: 90, communication: 88, retention: 95 },
    status: 'healthy' as const,
    lastReportDate: '2026-03-28',
    lastMeetingDate: '2026-04-02',
    nextMeetingDate: '2026-04-16',
    alerts: [],
    notes: 'Top performer. Upsell mogelijkheid: LinkedIn Ads voor corporate bookings.',
  },
  {
    clientName: 'Franky Amsterdam',
    accountManager: 'Ruben',
    vertical: 'Hospitality',
    contractStart: '2025-01-15',
    contractEnd: null,
    retainerValue: 3200,
    platforms: ['meta', 'google'],
    healthScore: 85,
    scores: { performance: 88, budgetPacing: 85, communication: 80, retention: 87 },
    status: 'healthy' as const,
    lastReportDate: '2026-03-31',
    lastMeetingDate: '2026-04-07',
    nextMeetingDate: '2026-04-21',
    alerts: [{ type: 'Budget', message: 'Google Ads slightly underpacing (-8%)', severity: 'low' as const }],
    notes: 'Happy client. Bezig met uitbreiding naar tweede locatie.',
  },
  {
    clientName: 'Conscious Hotels',
    accountManager: 'Koen',
    vertical: 'Hospitality',
    contractStart: '2024-09-01',
    contractEnd: '2026-09-01',
    retainerValue: 5000,
    platforms: ['meta', 'google'],
    healthScore: 88,
    scores: { performance: 92, budgetPacing: 88, communication: 82, retention: 90 },
    status: 'healthy' as const,
    lastReportDate: '2026-03-25',
    lastMeetingDate: '2026-03-27',
    nextMeetingDate: '2026-04-14',
    alerts: [],
    notes: 'Sterke ROAS verbeteringen. Seizoensgebonden: zomer is peak.',
  },
  {
    clientName: 'Refurbished.nl',
    accountManager: 'Koen',
    vertical: 'E-commerce',
    contractStart: '2025-03-01',
    contractEnd: null,
    retainerValue: 3500,
    platforms: ['meta', 'google'],
    healthScore: 91,
    scores: { performance: 95, budgetPacing: 92, communication: 85, retention: 92 },
    status: 'healthy' as const,
    lastReportDate: '2026-04-01',
    lastMeetingDate: '2026-04-03',
    nextMeetingDate: '2026-04-17',
    alerts: [],
    notes: 'Case study klant. POAS implementatie is differentiator.',
  },
  {
    clientName: 'Synvest',
    accountManager: 'Ruben',
    vertical: 'Finance',
    contractStart: '2026-02-01',
    contractEnd: null,
    retainerValue: 3800,
    platforms: ['google', 'linkedin'],
    healthScore: 72,
    scores: { performance: 65, budgetPacing: 78, communication: 70, retention: 75 },
    status: 'attention' as const,
    lastReportDate: '2026-03-15',
    lastMeetingDate: '2026-03-20',
    nextMeetingDate: null,
    alerts: [
      { type: 'Performance', message: 'CPA gestegen +23% in maart', severity: 'medium' as const },
      { type: 'Communicatie', message: 'Geen meeting gepland', severity: 'medium' as const },
    ],
    notes: 'Nieuwe klant, nog in optimalisatiefase. Financiële vertical is uitdagend.',
  },
  {
    clientName: 'ESTG',
    accountManager: 'Ruben',
    vertical: 'B2B',
    contractStart: '2026-03-15',
    contractEnd: null,
    retainerValue: 3800,
    platforms: ['google', 'linkedin'],
    healthScore: 78,
    scores: { performance: 75, budgetPacing: 82, communication: 78, retention: 77 },
    status: 'attention' as const,
    lastReportDate: null,
    lastMeetingDate: '2026-04-08',
    nextMeetingDate: '2026-04-22',
    alerts: [
      { type: 'Rapport', message: 'Nog geen rapport verstuurd', severity: 'high' as const },
    ],
    notes: 'Verse deal, moet tekenen. Contract bijna rond.',
  },
  {
    clientName: 'Solid Nature',
    accountManager: 'Koen',
    vertical: 'B2B',
    contractStart: '2025-08-01',
    contractEnd: '2026-08-01',
    retainerValue: 2500,
    platforms: ['google'],
    healthScore: 65,
    scores: { performance: 60, budgetPacing: 70, communication: 55, retention: 75 },
    status: 'attention' as const,
    lastReportDate: '2026-02-28',
    lastMeetingDate: '2026-03-10',
    nextMeetingDate: null,
    alerts: [
      { type: 'Communicatie', message: '31 dagen geen meeting', severity: 'high' as const },
      { type: 'Rapport', message: 'Rapport 41 dagen oud', severity: 'medium' as const },
    ],
    notes: 'Contract loopt over 4 maanden af. Renewal gesprek plannen.',
  },
  {
    clientName: 'Momentum Capital',
    accountManager: 'Ruben',
    vertical: 'Finance',
    contractStart: '2025-11-01',
    contractEnd: null,
    retainerValue: 4200,
    platforms: ['google', 'linkedin'],
    healthScore: 82,
    scores: { performance: 80, budgetPacing: 85, communication: 82, retention: 81 },
    status: 'healthy' as const,
    lastReportDate: '2026-03-30',
    lastMeetingDate: '2026-04-05',
    nextMeetingDate: '2026-04-19',
    alerts: [],
    notes: 'Goed lopend. Meeting gepland deze maand.',
  },
  {
    clientName: 'ParkBee',
    accountManager: 'Koen',
    vertical: 'B2B',
    contractStart: '2025-05-01',
    contractEnd: null,
    retainerValue: 3200,
    platforms: ['meta', 'google'],
    healthScore: 89,
    scores: { performance: 93, budgetPacing: 88, communication: 84, retention: 91 },
    status: 'healthy' as const,
    lastReportDate: '2026-04-01',
    lastMeetingDate: '2026-04-04',
    nextMeetingDate: '2026-04-18',
    alerts: [],
    notes: 'Multi-location succes. Case study geschreven.',
  },
  {
    clientName: 'MyPup',
    accountManager: 'Ruben',
    vertical: 'E-commerce',
    contractStart: '2026-04-01',
    contractEnd: null,
    retainerValue: 3200,
    platforms: ['meta', 'google'],
    healthScore: 70,
    scores: { performance: 60, budgetPacing: 75, communication: 80, retention: 65 },
    status: 'attention' as const,
    lastReportDate: null,
    lastMeetingDate: '2026-04-08',
    nextMeetingDate: '2026-04-22',
    alerts: [
      { type: 'Nieuw', message: 'Onboarding fase — baseline nog niet vastgesteld', severity: 'medium' as const },
    ],
    notes: 'Verse deal, direct offerte-fase. Moet snel waarde laten zien.',
  },
  {
    clientName: 'Mellow Resort',
    accountManager: 'Ruben',
    vertical: 'Hospitality',
    contractStart: '2026-03-01',
    contractEnd: null,
    retainerValue: 2000,
    platforms: ['meta', 'google'],
    healthScore: 74,
    scores: { performance: 70, budgetPacing: 80, communication: 72, retention: 74 },
    status: 'attention' as const,
    lastReportDate: null,
    lastMeetingDate: '2026-03-28',
    nextMeetingDate: null,
    alerts: [
      { type: 'Contract', message: 'Akkoord maar nog niet getekend', severity: 'high' as const },
      { type: 'Rapport', message: 'Nog geen rapport', severity: 'medium' as const },
    ],
    notes: 'Moet tekenen! €2K/mnd nieuwe MRR.',
  },
  {
    clientName: 'The Tire Group',
    accountManager: 'Koen',
    vertical: 'E-commerce',
    contractStart: '2024-11-01',
    contractEnd: null,
    retainerValue: 4000,
    platforms: ['meta', 'google'],
    healthScore: 87,
    scores: { performance: 90, budgetPacing: 86, communication: 84, retention: 88 },
    status: 'healthy' as const,
    lastReportDate: '2026-03-29',
    lastMeetingDate: '2026-04-02',
    nextMeetingDate: '2026-04-16',
    alerts: [],
    notes: 'Stabiele klant. Seizoenspieken in najaar (winterbanden).',
  },
  {
    clientName: 'Lofi Diamond',
    accountManager: 'Koen',
    vertical: 'E-commerce',
    contractStart: '2025-01-10',
    contractEnd: '2026-01-10',
    retainerValue: 2800,
    platforms: ['meta', 'google'],
    healthScore: 35,
    scores: { performance: 40, budgetPacing: 30, communication: 20, retention: 50 },
    status: 'critical' as const,
    lastReportDate: '2025-12-15',
    lastMeetingDate: '2026-01-15',
    nextMeetingDate: null,
    alerts: [
      { type: 'Churn Risk', message: 'Contract verlopen, 83 dagen geen contact', severity: 'high' as const },
      { type: 'Rapport', message: 'Laatste rapport 116 dagen oud', severity: 'high' as const },
      { type: 'Communicatie', message: '85 dagen geen meeting', severity: 'high' as const },
    ],
    notes: 'Waarschijnlijk churned. Verwijderen uit actieve lijst overwegen.',
  },
  {
    clientName: 'Abloom',
    accountManager: 'Ruben',
    vertical: 'Fashion',
    contractStart: '2025-01-08',
    contractEnd: '2026-01-08',
    retainerValue: 2500,
    platforms: ['meta'],
    healthScore: 30,
    scores: { performance: 35, budgetPacing: 25, communication: 15, retention: 45 },
    status: 'critical' as const,
    lastReportDate: '2025-11-30',
    lastMeetingDate: '2026-02-07',
    nextMeetingDate: null,
    alerts: [
      { type: 'Churn Risk', message: 'Contract verlopen, 61 dagen geen contact', severity: 'high' as const },
      { type: 'Rapport', message: 'Laatste rapport 131 dagen oud', severity: 'high' as const },
    ],
    notes: 'Waarschijnlijk churned. Was al 93d in pipeline zonder actie.',
  },
  {
    clientName: 'SafeScan',
    accountManager: 'Koen',
    vertical: 'B2B',
    contractStart: '2025-04-01',
    contractEnd: null,
    retainerValue: 3500,
    platforms: ['google', 'linkedin'],
    healthScore: 84,
    scores: { performance: 85, budgetPacing: 82, communication: 86, retention: 83 },
    status: 'healthy' as const,
    lastReportDate: '2026-03-27',
    lastMeetingDate: '2026-04-03',
    nextMeetingDate: '2026-04-17',
    alerts: [],
    notes: 'Goed lopend. LinkedIn Ads performen boven verwachting.',
  },
]

async function seed() {
  console.log(`Seeding ${clients.length} clients to ${DASHBOARD_URL}/api/client-health...`)
  
  const res = await fetch(`${DASHBOARD_URL}/api/client-health`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ clients }),
  })
  
  const data = await res.json()
  console.log('Result:', data)
}

seed().catch(console.error)
